aws:
    region: eu-central-1
    user:
        profile: default
kinesis:
    video:
        stream:
            content_type: video/h264
            name: traffic-guard
sources:
    webcam:
        device:
            description: Desktop PC Web Camera
            fps: 25
            name: Logitech HD Webcam C270 0
            resolution: VGA
            type: PC Cam
        queue_length: 100
